# Generated by Django 4.1.3 on 2022-11-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qbo_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qbo_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='qbo_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
