# Generated by Django 4.1.3 on 2022-11-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_client_qbo_id_invoice_qbo_id_item_qbo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='qbo_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
